webhook_create_order_body =  {
    "order_id": "24",
    "user_id": "11",
    "date": "2020-10-29 20:53:19",
    "status_date": "2020-10-29 20:53:19",
    "confirm_date": "0000-00-00 00:00:00",
    "delivery_date": "0000-00-00",
    "status_id": "1",
    "sum": "497.67",
    "payment_id": "17",
    "user_order": "2",
    "shipping_id": "1",
    "shipping_cost": "0.00",
    "email": "my@mail.com",
    "delivery_code": "",
    "code": "d0b080c93533b53785584ff3ab3d3f56",
    "confirm": "0",
    "notes": "agagahahahv4yw h7igbig0bggwb pbgiowb08g 08 gbgobq8b0",
    "notes_priv": "",
    "notes_pub": "",
    "currency_id": "1",
    "currency_rate": "1",
    "paid": "0.00",
    "ip_address": "193.25.0.20",
    "discount_client": "0",
    "discount_group": "0",
    "discount_levels": "0",
    "discount_code": "0",
    "shipping_vat": "1",
    "shipping_vat_value": "23",
    "shipping_vat_name": "23%",
    "code_id": "null",
    "lang_id": "1",
    "origin": "0",
    "parent_order_id": "null",
    "registered": "1",
    "billingAddress": {
        "address_id": "25",
        "order_id": "24",
        "type": "1",
        "firstname": "MarcinRR",
        "lastname": "Surname",
        "company": "",
        "tax_id": "44444444444444444444",
        "pesel": "",
        "city": "Krak\\u00f3w",
        "postcode": "31-572",
        "street1": "ulica 33",
        "street2": "",
        "state": "",
        "country": "Polska",
        "phone": "123456789",
        "country_code": "PL"
    },
    "deliveryAddress": {
        "address_id": "25",
        "order_id": "24",
        "type": "1",
        "firstname": "MarcinRR",
        "lastname": "Surname",
        "company": "",
        "tax_id": "",
        "pesel": "",
        "city": "Krak\\u00f3w",
        "postcode": "31-572",
        "street1": "ulica 33",
        "street2": "",
        "state": "",
        "country": "Polska",
        "phone": "123456789",
        "country_code": "PL"
    },
    "currency_name": "PLN",
    "shipping": {
        "shipping_id": "1",
        "cost": "0.00",
        "depend_on_w": "0",
        "tax_id": "1",
        "max_weight": "0",
        "min_weight": "0",
        "free_shipping": "0",
        "order": "9",
        "pkwiu": "",
        "mobile": "1",
        "engine": "personal",
        "zone_id": "1",
        "callback_url": "",
        "warehouse_id": "null",
        "translation_id": "1",
        "name": "odbi\\u00f3r osobisty",
        "description": "odbi\\u00f3r w siedzibie firmy",
        "is_default": "1"
    },
    "status": {
        "status_id": "1",
        "default": "1",
        "color": "",
        "type": "1",
        "email_change": "0",
        "order": "1",
        "name": "z\\u0142o\\u017cone",
        "message": "z\\u0142o\\u017cone"
    },
    "payment": {
        "payment_id": "17",
        "name": "transfer",
        "order": "0",
        "title": "Przelew",
        "description": "",
        "notify_mail": "<p>|<\\/p>\\r\\n<p>|<\\/p>\\r\\n<p>|<\\/p>\\r\\n<p><strong>{order_id}<\\/strong>\\u00a0- numer zam\\u00f3wienia<br \\/><strong>{sum}<\\/strong>\\u00a0- warto\\u015b\\u0107 zam\\u00f3wienia, z walut\\u0105<br \\/><strong>{float_sum}<\\/strong>\\u00a0- warto\\u015b\\u0107 zam\\u00f3wienia, bez waluty<\\/p>\\r\\n<p>|<\\/p>\\r\\n<p>|<\\/p>\\r\\n<p>|<\\/p>"
    },
    "promo_code": "",
    "products": [
        {
            "id": "44",
            "order_id": "24",
            "product_id": "444",
            "stock_id": "451",
            "price": "165.89",
            "discount_perc": "0.0000",
            "quantity": "3",
            "delivery_time": 0,
            "name": "D\\u0142awnica standardowa DS 100\\/60",
            "code": "DS100060082",
            "pkwiu": "",
            "tax": "23%",
            "tax_value": "23",
            "unit": "szt.",
            "option": "",
            "unit_fp": "0",
            "weight": "3.13",
            "type": "0",
            "loyalty": "0",
            "delivery_time_hours": "0",
            "text_options": [],
            "file_options": []
        },
        {
            "id": "44",
            "order_id": "24",
            "product_id": "444",
            "stock_id": "451",
            "price": "165.89",
            "discount_perc": "0.0000",
            "quantity": "3",
            "delivery_time": 0,
            "name": "D\\u0142awnica standardowa DS 100\\/60",
            "code": "DS100060082",
            "pkwiu": "",
            "tax": "23%",
            "tax_value": "23",
            "unit": "szt.",
            "option": "",
            "unit_fp": "0",
            "weight": "3.13",
            "type": "0",
            "loyalty": "0",
            "delivery_time_hours": "0",
            "text_options": [],
            "file_options": []
        }
    ],
    "additional_fields": [
        {
            "field_id": "2",
            "type": "2",
            "locate": "104",
            "req": "1",
            "active": "1",
            "order": "2",
            "value": "1"
        },
        {
            "field_id": "3",
            "type": "2",
            "locate": "120",
            "req": "0",
            "active": "1",
            "order": "3",
            "value": ""
        }
    ],
    "children": []
}

fakturownia_customers_by_id = [
    {
        "id": 39498583,
        "name": "Marcin Kukla",
        "tax_no": "123456789",
        "post_code": "31-572",
        "city": "Kraków",
        "street": "ulica 00",
        "first_name": "",
        "country": "",
        "email": "mrcn.kkl@gmail.com",
        "phone": "48123456789",
        "www": "",
        "fax": "",
        "created_at": "2020-10-26T19:08:02.000+01:00",
        "updated_at": "2020-11-06T21:35:05.000+01:00",
        "street_no": None,
        "kind": "buyer",
        "bank": "",
        "bank_account": "",
        "bank_account_id": None,
        "shortcut": "Marcin Kukla",
        "note": "",
        "last_name": "",
        "referrer": None,
        "token": "FhJaswgPbpfftXY76dA",
        "fuid": None,
        "fname": None,
        "femail": None,
        "dynamic_fields": {
            "default_tax": "",
            "identity_card_series": "",
            "identity_card_number": "",
            "identity_card_issue_date": "",
            "identity_card_issue_authority": ""
        },
        "department_id": 403428,
        "import": None,
        "discount": None,
        "payment_to_kind": "",
        "category_id": None,
        "use_delivery_address": False,
        "delivery_address": "",
        "person": "",
        "panel_user_id": None,
        "use_mass_payment": False,
        "mass_payment_code": None,
        "external_id": "",
        "company": True,
        "title": None,
        "mobile_phone": "",
        "register_number": "",
        "tax_no_check": "PL123456789",
        "attachments_count": 0,
        "default_payment_type": "",
        "tax_no_kind": "",
        "accounting_id": "",
        "disable_auto_reminders": False,
        "buyer_id": None,
        "price_list_id": None,
        "panel_url": "https://viti.fakturownia.pl/panel/FhJaswgPbpfftXY76dA"
    },
    {
        "id": 40110338,
        "name": "test",
        "tax_no": "123456789",
        "post_code": "12-345",
        "city": "test",
        "street": "test",
        "first_name": "test",
        "country": "",
        "email": "test@test.test",
        "phone": "87654321",
        "www": "",
        "fax": "",
        "created_at": "2020-11-06T21:36:16.000+01:00",
        "updated_at": "2020-11-06T21:36:16.000+01:00",
        "street_no": None,
        "kind": "buyer",
        "bank": "",
        "bank_account": "",
        "bank_account_id": None,
        "shortcut": "test",
        "note": "test",
        "last_name": "test",
        "referrer": None,
        "token": "a4QvqSTc4saxhcUC4EF",
        "fuid": None,
        "fname": None,
        "femail": None,
        "dynamic_fields": {
            "default_tax": "",
            "identity_card_series": "",
            "identity_card_number": "",
            "identity_card_issue_date": "",
            "identity_card_issue_authority": ""
        },
        "department_id": None,
        "import": None,
        "discount": None,
        "payment_to_kind": "",
        "category_id": None,
        "use_delivery_address": False,
        "delivery_address": "",
        "person": "",
        "panel_user_id": None,
        "use_mass_payment": False,
        "mass_payment_code": None,
        "external_id": "",
        "company": True,
        "title": None,
        "mobile_phone": "",
        "register_number": "",
        "tax_no_check": "PL123456789",
        "attachments_count": 0,
        "default_payment_type": "",
        "tax_no_kind": "",
        "accounting_id": "",
        "disable_auto_reminders": False,
        "buyer_id": None,
        "price_list_id": None,
        "panel_url": "https://viti.fakturownia.pl/panel/a4QvqSTc4saxhcUC4EF"
    }
]